DROP TABLE IF EXISTS ZIP_CODE;

CREATE TABLE ZIP_CODE(
    NUM_POSTAL_CODE INTEGER NOT NULL,
    STR_STREET VARCHAR(255),
    STR_CITY VARCHAR(255) NOT NULL,
    STR_STATE VARCHAR(255) NOT NULL,
    STR_NEIGHBORHOOD VARCHAR(255),
    STR_IBGECODE INTEGER NOT NULL
);

ALTER TABLE ZIP_CODE ADD CONSTRAINT PK_POSTALCODE PRIMARY KEY (
    NUM_POSTAL_CODE
);